basePath: /
definitions:
  params.RegisterUserRs:
    properties:
      age:
        type: integer
      email:
        type: string
      error:
        type: string
      id:
        type: integer
      message:
        type: string
      status:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server todo server. You can visit the GitHub repository
    at https://github.com/LordGhostX/swag-gin-demo
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go + Gin Todo API
  version: "1.0"
paths:
  /users:
    get:
      operationId: get-all-users
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/params.RegisterUserRs'
      summary: get all users
swagger: "2.0"
